spring.application.name: "diffy"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

server:
  port: ${http.port:8888}

proxy:
  port: 8880

candidate: "localhost:9000"

master:
  primary: "localhost:9100"
  secondary: "localhost:9200"

service:
  protocol : "http"

serviceName : "Sample Service"
